version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from protos"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
